server.port=8080
spring.application.name=products-api

spring.datasource.initialize=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
