apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsapideployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: productscontainer
        image: afsal790/products_api:latest
        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://database-1.c8f6gg6ae07d.us-east-1.rds.amazonaws.com:3306/ecommerce"

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: productssvc
spec:
  type: LoadBalancer
  selector:
    app: products
  ports:
  - port: 80
    targetPort: 8080



