pipeline {
    agent any
    
    tools{
        maven "maven"
    }    

    stages {

        stage('Git Clone') {
            steps {
               git branch: 'main', url: 'https://github.com/lrnngdevops-spec/project-3.git'
            }
        }

        stage('Maven Build'){
            steps{
                dir('01_products_api'){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Image'){
            steps{
                dir('01_products_api'){
                    sh 'docker build -t devikabraj/products_api .'
                }
            }
        }

        stage('Docker Push'){
            steps{
                withCredentials([string(credentialsId: 'docker_pwd', variable: 'docker_pwd')]) {
                   sh 'docker login -u devikabraj -p ${docker_pwd}'
                   sh 'docker push devikabraj/products_api'
                }
            }
        }

        stage('Kubernetes Deploy'){
            steps{
                sh 'kubectl apply -f Deployment.yml'
            }
        }
    }
}
